### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by metacatdud** [herenow/light-router#1]
Hi man, 

I was looking around for a small and very light routing system and looks like yours is closest of what i'm looking for. 

I was looking around your code an i've seen you do some trimming at a point. My question is what if the route is the homepage "/"? After trimming will be "" ? Is this correct?

Thanks man :)

**Comment by herenow** [comment]
Sorry for the late response.

Yep, after trimming "/" will become "", and after splitting "", it will become an empty array, so it will be placed on top of the routing tree/table.
